### ISSUE TITLE
canonicalize-missing: No such file or directory

### ISSUE THREAD

**Issue by barebu** [WoozyMasta/kube-dump#13]
Hi
Thanks for this wonderful tool. I Have Centos 7.8 and try to run kube-dump 1.0 in Docker:

`docker run --interactive --volume /home/kubernetesadmin/.kube:/.kube --volume /home/kubernetesadmin/dump:/dump woozymasta/kube-dump:1.0 dump-namespaces -n dev -d /dump --kube-config /.kube/config`
 
and get:
`realpath: --canonicalize-missing: No such file or directory`

On version 1.0.0 or earliest everything is fine.

**Comment by WoozyMasta** [comment]
Thanks for the feedback, the problem was fixed in the 9ac0c6b7c7eb85005125c089bbff52fa1e0c9d99 commit.

Released version [1.0.4](https://github.com/WoozyMasta/kube-dump/releases/tag/v1.0.4)
