### ISSUE TITLE
Error on GIT

### ISSUE THREAD

**Issue by YuriBucci2** [WoozyMasta/kube-dump#19]
Hello guys I found a issue when use git push:

grep: unrecognized option: quiet

I added this options in Dockefile and worked:

apk add --no-cache --upgrade grep

**Comment by WoozyMasta** [comment]
@YuriBucci2, good work! Thank you.

Fixed in version [1.0.6](https://github.com/WoozyMasta/kube-dump/releases/tag/v1.0.6) e5365d9cece38fe983ef14186e4776424ecf46f8
