### ISSUE TITLE
There is no reference for kube-dump secret in the documentation at git key cronjob.

### ISSUE THREAD

**Issue by devopstales** [WoozyMasta/kube-dump#20]
In cronjob-git-key.yaml her is a part for a secret called kube-dump to use:

```
              envFrom:
                - secretRef:
                    name: kube-dump
```

There is no reference for this secret in the documentation.

**Comment by WoozyMasta** [comment]
@devopstales , thanks for your assistance, fixed in the commit https://github.com/WoozyMasta/kube-dump/commit/fbbf9f727db4dcd9cd3c7701fc688159465c15ea

Yes, the link to the secret got there by accident.
