### ISSUE TITLE
kube_api_token not being filled

### ISSUE THREAD

**Issue by rcomanne** [WoozyMasta/kube-dump#24]
I was trying to implement this script into a custom Docker container based on Alpine.
Everything seemed allright, but when I try to run the container as a job, it would be stuck in startup, claiming to retrieve 401's from k8s' API.  
After doing some digging in the container and trying to execute the script myself, it turned out that somehow the api token was not filled. Filling the token variable by hand with a cat and executing the health check with the same command, it now succeeds.  
I do not know why exactly, but filling with `kube_api_token=$(</token/path)` does not work while `kube_api_token=$(cat /token/path)` does work.

My Dockerfile for reference;  
```
FROM woozymasta/kube-dump:1.0

# Add 'kubedump' user
ARG user=kubedump
ARG group=kubedump
ARG uid=1000
ARG gid=1000
ARG home_dir=/home/kubedump

ENV HOME ${home_dir}

RUN apk upgrade --no-cache \
    && addgroup --system ${group} --gid ${gid} \
    && adduser --system --uid ${uid} --home "$HOME" --ingroup ${group} --shell /bin/ash ${user} \
    && mkdir ${home_dir}/.ssh \
    && chmod 0700 ${home_dir}/.ssh \
    && chown -R ${user}:${group} ${home_dir} \
    && mv /kube-dump /usr/bin/kube-dump \
    && chmod a+x /usr/bin/kube-dump

# Switch context
WORKDIR ${home_dir}
USER ${user}

ENTRYPOINT [ "kube-dump" ]
```

**Comment by WoozyMasta** [comment]
Hi, thanks for the feedback.

It looks like sh is being used instead of bash
You can check the same using the latest version 1.0.6.

```dockerfile
FROM woozymasta/kube-dump:1.0.6
```
