### ISSUE TITLE
kube-dump exclude=events

### ISSUE THREAD

**Issue by julianobarbosa** [WoozyMasta/kube-dump#25]
is possible dump without events ?

**Comment by WoozyMasta** [comment]
In the current implementation, if you do not specify a specific list of namespaces or resources, all resources available to the user will be saved according to the RBAC policy.

If there is a need to save only certain types of resources, specify them in the list through the configuration parameters:

Arguments `-n`, `--namespaces`, or the `NAMESPACES` variable to list specific namespaces.
 Arguments `-r`, `--namespaced-resources`, or the `NAMESPACED_RESOURCES` variable to list specific resource types.

For example:

```bash
./kube-dump ns -n dev,prod -r deployment,sts,ds,svc
# or
MODE=ns NAMESPACES=dev,prod NAMESPACED_RESOURCES=deployment,sts,ds,svc ./kube-dump
```

The kubernetes resource types you can get from `kubectl api-resources` or from the [documentation page](https://kubernetes.io/docs/reference/kubectl/overview/#resource-types)
