### ISSUE TITLE
does not work in ubuntu

### ISSUE THREAD

**Issue by robertchen** [WoozyMasta/kube-dump#35]
$ ./kube-dump all
./kube-dump: line 21: $'\r': command not found
./kube-dump: line 23: $'\r': command not found
./kube-dump: line 25: syntax error near unexpected token `$'{\r''
'/kube-dump: line 25: `log () {

**Comment by WoozyMasta** [comment]
I suspect that you copied the script's source code to the Windows clipboard or saved the file with incorrect CRLF line endings.

Try downloading the file with curl or using a docker image

Or fix with:
```bash
sed -i 's/\r$//' ./kube-dump
```

there is no `\r` in the source file, only `\n`
