### ISSUE TITLE
Kube-dump fails

### ISSUE THREAD

**Issue by laincorp** [WoozyMasta/kube-dump#37]
Hello, 

kube-dump fails to fill up the yaml files, 
the connection to the cluster works, 
in fact he can see al resources,
but the files are empty and there is a series of failures : 
the kubeconfig is passed to the command, or in environment,
the result is the same.

# ./kube-dump all
Dump data in /root/data directory
  
Dump namespace alert-dispatcher started
STATE          RESOURCE                      NAME
Failed        configmaps                   kube-root-ca.crt
Failed        endpoints                      publisher
Failed        events                           alert-publisher-7db85b76d8-kwgf5.17051a2a89149f67
Failed        events                           alert-publisher-7db85b76d8-kwgf5.17051a2a91a3af76
Failed        events                           alert-publisher-7db85b76d8-kwgf5.17051a2a91a3cd0f

I have yq and jq binaries in /bin
I run those commands from an ubuntu machine,

how can i troubleshoot further ?
what can be the reasons for this failures ?

thanks in advance

**Comment by WoozyMasta** [comment]
Can you provide debug messages?
By running with `bash -x ./kube-dump`

**Comment by hkpanchani** [comment]
```
+ read -r name
+ '[' -z fluentd-tm3-config ']'
+ '[' configmaps == secret ']'
+ msg-start configmaps fluentd-tm3-config
+ '[' '' == true ']'
+ '[' -t 1 ']'
+ printf '\e[1;33m%-15s\e[m%-30s%s\n' Processing configmaps fluentd-tm3-config
Processing     configmaps                    fluentd-tm3-config
+ destination_resource_name=fluentd-tm3-config_configmaps.yaml
+ kubectl --namespace=uat-tm3 get --output=json configmaps fluentd-tm3-config
+ yq eval --prettyPrint --no-colors --exit-status -
+ jq --exit-status --compact-output --monochrome-output --raw-output --sort-keys '  del(
    .metadata.annotations."autoscaling.alpha.kubernetes.io/conditions",
    .metadata.annotations."autoscaling.alpha.kubernetes.io/current-metrics",
    .metadata.annotations."control-plane.alpha.kubernetes.io/leader",
    .metadata.annotations."deployment.kubernetes.io/revision",
    .metadata.annotations."kubectl.kubernetes.io/last-applied-configuration",
    .metadata.annotations."kubernetes.io/service-account.uid",
    .metadata.annotations."pv.kubernetes.io/bind-completed",
    .metadata.annotations."pv.kubernetes.io/bound-by-controller",
    .metadata.finalizers,
    .metadata.managedFields,
    .metadata.creationTimestamp,
    .metadata.generation,
    .metadata.resourceVersion,
    .metadata.selfLink,
    .metadata.uid,
    .spec.clusterIP,
    .spec.progressDeadlineSeconds,
    .spec.revisionHistoryLimit,
    .spec.template.metadata.annotations."kubectl.kubernetes.io/restartedAt",
    .spec.template.metadata.creationTimestamp,
    .spec.volumeName,
    .spec.volumeMode,
    .status
  )'
+ msg-fail configmaps fluentd-tm3-config
+ '[' '' == true ']'
+ '[' -t 1 ']'
Fail           configmaps                    fluentd-tm3-configntd-tm3-config
````
